name: sync-to-dev
on:
  push:
    branches:
      - main
      - 'hotfix-*'
      - 'release-*'
jobs:
  sync-to-dev:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
       - name: Checkout code
         uses: actions/checkout@v2
         with:
            fetch-depth: 0    
       - name: Rebase
         run: |
          git config --global user.email github-actions@github.com
          git config --global user.name github-actions
          
          BRANCH_NAME=$(echo "${{ github.ref }}" | sed 's/refs\/heads\///')
          
          git checkout $BRANCH_NAME
          git checkout dev
          git rebase --onto $BRANCH_NAME dev
          # git config pull.rebase true
          git pull --rebase origin dev
          git push
